# Limpieza de datos

La mayoría de la gente piensa que ser científico de datos significa estar corriendo modelos avanzados de Machine Learning todo el tiempo. La realidad es muy distinta:

![Tiempo de un científico de datos](./img/datascientist_time.jpeg)

La gran mayoría del tiempo se va **limpiando y organizando** los datos con los que queremos trabajar.

Los científicos de datos utilizamos herramientas como Pandas, Numpy, Matplotlib y Seaborn para limpiar los datos con los que queremos hacer algo.

## ETL

Un tipo de tarea que realizamos con gran frecuencia los científicos de datos son los **ETL**.

![Proceso de ETL](./img/etl.png)

ETL es un acrónimo que significa Extract, Transform, Load. Es un proceso que se utiliza para extraer datos de una fuente, transformarlos en un formato que sea adecuado para el análisis y cargarlos en una base de datos o algún otro sistema de almacenamiento.

## Ejemplo práctico

Los datos que usaremos para esta limpieza y nuestro siguiente análisis son datos de incidencia delictiva en nuestro país.

La iniciativa de datos abiertos del gobierno de México nos proporciona datos de incidencia delictiva desde 2015 hasta la fecha. Los datos se actualizan todos los meses y se pueden descargar desde el siguiente enlace: https://www.gob.mx/sesnsp/acciones-y-programas/datos-abiertos-de-incidencia-delictiva

---

Como podemos ver en el portal, se proporcionan los datos tanto a nivel estatal como a nivel municipal. En este caso, utilizaremos los datos a nivel estatal.

Descarguemos los datos y guardemos el archivo CSV en la carpeta data con el nombre `datos_delitos.csv`.

---

Ahora leamos el archivo CSV y veamos cómo se ven los datos.

Primero que nada, importemos pandas

In [ ]:
import pandas as pd

In [2]:
df = pd.read_csv('data/datos_delitos.csv')

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 1: invalid continuation byte

Aquí tenemos un error muy común que suele ocurrir cuando un archivo se guarda en una computadora con cierto "encoding". 

Un encoding es una tabla que relaciona un número con un carácter. Por ejemplo, en la tabla ASCII, el número 65 corresponde a la letra "A".

Si el archivo que estamos leyendo fue guardado con un encoding distinto al que pandas espera, nos arrojará un error. 

Para solucionar esto, podemos utilizar el parámetro `encoding` de la función `pd.read_csv()` y especificar el encoding correcto.

¿Pero cómo sabemos con qué encoding cuenta el archivo?

La realidad es que la gran mayoría de los archivos los encontrarán en encoding utf-8 y Pandas no va a dar ningún error. Aquí estamos teniendo este problema porque la computadora que utilizan para generar este archivo uso un encoding diferente a utf-8.

En México, por lo general, si un archivo no está en utf-8, lo más seguro es que esté en `ISO-8859-1` o `latin1`.

Intentemos cargar el archivo especificando el encoding `ISO-8859-1`.

In [3]:
df = pd.read_csv('data/datos_delitos.csv', encoding='ISO-8859-1')
df.head()

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0
2,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,2,2,3,2,0.0,1.0,2.0,0.0,0.0,0.0
3,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,No especificado,2,0,0,1,0,0,0.0,0.0,0.0,0.0,0.0,0.0
4,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio culposo,Con arma de fuego,0,0,0,0,1,0,0.0,0.0,0.0,0.0,0.0,0.0

Y vemos que ya podemos leer correctamente el archivo.


¿Existe alguna forma de verificar el encoding de un archivo sin tener que estar adivinando?

ChatGTP generó el siguiente código:

In [4]:
import chardet

def detect_encoding(file_path):
    with open(file_path, 'rb') as f:
        rawdata = f.read()
    result = chardet.detect(rawdata)
    return result

file_path = './data/datos_delitos.csv'
encoding_info = detect_encoding(file_path)
print(f"Detected encoding: {encoding_info['encoding']}")

Detected encoding: Windows-1252

Sigamos...

In [5]:
df.tail(3)

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
31357,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,Delitos cometidos por servidores públicos,20,22,34,35,34,37,NaN,NaN,NaN,NaN,NaN,NaN
31358,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Electorales,Electorales,Electorales,0,1,0,11,31,23,NaN,NaN,NaN,NaN,NaN,NaN
31359,2024,32,Zacatecas,Otros bienes jurídicos afectados (del fuero co...,Otros delitos del Fuero Común,Otros delitos del Fuero Común,Otros delitos del Fuero Común,151,183,174,199,208,177,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31360 entries, 0 to 31359
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Año                     31360 non-null  int64
 1   Clave_Ent               31360 non-null  int64
 2   Entidad                 31360 non-null  str
 3   Bien jurídico afectado  31360 non-null  str
 4   Tipo de delito          31360 non-null  str
 5   Subtipo de delito       31360 non-null  str
 6   Modalidad               31360 non-null  str
 7   Enero                   31360 non-null  int64
 8   Febrero                 31360 non-null  int64
 9   Marzo                   31360 non-null  int64
 10  Abril                   31360 non-null  int64
 11  Mayo                    31360 non-null  int64
 12  Junio                   31360 non-null  int64
 13  Julio                   28224 non-null  float64
 14  Agosto                  28224 non-null  float64
 15  Septiembre              28224 non-null  float64
 16  Octubre                 28224 non-null  float64
 17  Noviembre               28224 non-null  float64
 18  Diciembre               28224 non-null  float64
dtypes: float64(6), int64(8), str(5)
memory usage: 4.5 MB

Bien. Están muy bien los datos. Sin embargo, tenemos un problema con el que es muy común encontrarnos. 

Resulta que el formato en el que está el archivo es fácil entender por seres humanos:


```markdown
| Año      | Entidad  | Enero    | Febrero  | Mes X    |
|----------|----------|----------|----------|----------|
|   ...    |   ...    |   ...    |   ...    |   ...    |
|   ...    |   ...    |   ...    |   ...    |   ...    |
|   ...    |   ...    |   ...    |   ...    |   ...    |
|   ...    |   ...    |   ...    |   ...    |   ...    |
|   ...    |   ...    |   ...    |   ...    |   ...    |
```

Vemos que tenemos los meses como encabezados. Es decir, el archivo está tratando cada mes como si fuera una variable. 

Nosotros como científicos de datos estamos más interesados en conjuntos de datos que no estén en este formato de "resumen" o "tabla dinámica". Para nosotros, lo ideal sería que cada mes fuera simplemente una observación más en nuestro conjunto de datos. Es decir, queremos transformar la tabla de arriba en:

```markdown
| Año      | Entidad  | Mes        |
|----------|----------|------------|
|   ...    |   ...    |   Enero    |
|   ...    |   ...    |   Febrero  |
|   ...    |   ...    |   Marzo    |
|   ...    |   ...    |   Abril    |
|   ...    |   ...    |   Mes X    |
```

A este tipo de formato le llamos "formato largo de datos".

Haremos las siguientes limpiezas:
* Transformar los nombres de las columnas para que no tengan caracteres especiales y estén siempre en minúsculas
* Convertir el dataset a un formato de datos "largo"

In [7]:
for col in df.columns:
    print(col)

Año
Clave_Ent
Entidad
Bien jurídico afectado
Tipo de delito
Subtipo de delito
Modalidad
Enero
Febrero
Marzo
Abril
Mayo
Junio
Julio
Agosto
Septiembre
Octubre
Noviembre
Diciembre

In [8]:
len(df.columns)

19

### Limpiar nombres de columnas

In [9]:
def limpiar_columnas(df):
    columnas_limpias = []
    for col in df.columns:
        # convertir a minusculas, reemplazar espacios por guiones bajos y eliminar caracteres especiales
        col = col.lower().replace(" ", "_").replace("ñ", "ni").replace(".", "").replace("á", "a").replace("é", "e").replace("í","i").replace("ó", "o").replace("ú", "u")
        columnas_limpias.append(col)
    
    df.columns = columnas_limpias
    
    return df

In [10]:
df.head(2)

,Año,Clave_Ent,Entidad,Bien jurídico afectado,Tipo de delito,Subtipo de delito,Modalidad,Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0

In [11]:
df = limpiar_columnas(df)

In [12]:
df.head(3)

,anio,clave_ent,entidad,bien_juridico_afectado,tipo_de_delito,subtipo_de_delito,modalidad,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
0,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0
2,2015,1,Aguascalientes,La vida y la Integridad corporal,Homicidio,Homicidio doloso,Con otro elemento,0,0,2,2,3,2,0.0,1.0,2.0,0.0,0.0,0.0

Muy bien. Ahora lo que queremos hacer es quitar algunas columnas. Nos interesan nada más las siguientes:

In [13]:
df[['anio', 'entidad']]

       anio         entidad
0      2015  Aguascalientes
1      2015  Aguascalientes
2      2015  Aguascalientes
3      2015  Aguascalientes
4      2015  Aguascalientes
...     ...             ...
31355  2024       Zacatecas
31356  2024       Zacatecas
31357  2024       Zacatecas
31358  2024       Zacatecas
31359  2024       Zacatecas

[31360 rows x 2 columns]

In [14]:
df = df[['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'subtipo_de_delito', 'modalidad','enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre']]
df.head(2)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,modalidad,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre
0,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma de fuego,3,0,2,1,1,1,2.0,1.0,2.0,2.0,2.0,1.0
1,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma blanca,1,1,0,0,0,1,0.0,1.0,0.0,0.0,0.0,1.0

### Formato largo de datos

Ahora, usaremos el método `melt` para convertir las columnas a observaciones.

Queremos convervar las coumnas:
* anio
* clave_ent
* entidad
* tipo_de_delito
* subtipo_de_delito
* modalidad

El resto de las columnas las vamos a juntar en una nueva columna llamada "nombre_mes" y sus valores los vamos a sumar en otra llamada "frecuencia"

In [15]:
print("Shape ", df.shape)

Shape  (31360, 18)

In [16]:
datos_long = df.melt(id_vars=['anio', 'clave_ent', 'entidad','tipo_de_delito', 'subtipo_de_delito', 'modalidad'], var_name='nombre_mes', value_name='frecuencia')

In [17]:
print("Shape: ", datos_long.shape)

Shape:  (376320, 8)

In [18]:
datos_long.head(5)

,anio,clave_ent,entidad,tipo_de_delito,subtipo_de_delito,modalidad,nombre_mes,frecuencia
0,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma de fuego,enero,3.0
1,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con arma blanca,enero,1.0
2,2015,1,Aguascalientes,Homicidio,Homicidio doloso,Con otro elemento,enero,0.0
3,2015,1,Aguascalientes,Homicidio,Homicidio doloso,No especificado,enero,2.0
4,2015,1,Aguascalientes,Homicidio,Homicidio culposo,Con arma de fuego,enero,0.0

In [19]:
datos_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 376320 entries, 0 to 376319
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   anio               376320 non-null  int64
 1   clave_ent          376320 non-null  int64
 2   entidad            376320 non-null  str
 3   tipo_de_delito     376320 non-null  str
 4   subtipo_de_delito  376320 non-null  str
 5   modalidad          376320 non-null  str
 6   nombre_mes         376320 non-null  str
 7   frecuencia         357504 non-null  float64
dtypes: float64(1), int64(2), str(5)
memory usage: 23.0 MB

Supongamos que para este análisis, no nos importan los niveles subtipo de delito y modalidad. O sea, no queremos tener la distinción entre homicidios dolosos y culposos (sé que son bastante diferentes, pero simplifiquemos nuestro ejemplo).

Vamos a agrupar nuestro dataframe por anio, clave_ent, entidad, tipo_de_delito y nombre_mes. Esto hará que todos los tipos de homicidios se sumen al tipo "homicidio" o todos los tipos de robo de vehículo (con o sin violencia) se sumen a "robo de vehículo".

In [20]:
datos_long = datos_long.groupby(['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'nombre_mes'])['frecuencia'].sum().reset_index()

In [21]:
datos_long[datos_long.tipo_de_delito == 'Robo'].sample(15)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia
74788,2019,28,Tamaulipas,Robo,febrero,1074.0
105028,2021,27,Tabasco,Robo,febrero,941.0
112228,2022,10,Durango,Robo,febrero,503.0
126149,2023,7,Chiapas,Robo,julio,188.0
46475,2018,1,Aguascalientes,Robo,septiembre,1158.0
43111,2017,26,Sonora,Robo,marzo,1239.0
106472,2021,30,Veracruz de Ignacio de la Llave,Robo,mayo,1947.0
107429,2021,32,Zacatecas,Robo,julio,463.0
9025,2015,19,Nuevo León,Robo,agosto,1321.0
48388,2018,5,Coahuila de Zaragoza,Robo,febrero,723.0
83914,2020,15,México,Robo,octubre,12137.0
36390,2017,12,Guerrero,Robo,junio,811.0
83425,2020,14,Jalisco,Robo,agosto,4448.0
13828,2015,29,Tlaxcala,Robo,febrero,344.0
116554,2022,19,Nuevo León,Robo,octubre,1450.0

Mostremos todos los estados y su respectiva clave

In [22]:
datos_long[['clave_ent', 'entidad']].drop_duplicates().sort_values('entidad')

       clave_ent                          entidad
0              1                   Aguascalientes
480            2                  Baja California
960            3              Baja California Sur
1440           4                         Campeche
2880           7                          Chiapas
3360           8                        Chihuahua
3840           9                 Ciudad de México
1920           5             Coahuila de Zaragoza
2400           6                           Colima
4320          10                          Durango
4800          11                       Guanajuato
5280          12                         Guerrero
5760          13                          Hidalgo
6240          14                          Jalisco
7200          16              Michoacán de Ocampo
7680          17                          Morelos
6720          15                           México
8160          18                          Nayarit
8640          19                       Nuevo León
9120          20                           Oaxaca
9600          21                           Puebla
10080         22                        Querétaro
10560         23                     Quintana Roo
11040         24                  San Luis Potosí
11520         25                          Sinaloa
12000         26                           Sonora
12480         27                          Tabasco
12960         28                       Tamaulipas
13440         29                         Tlaxcala
13920         30  Veracruz de Ignacio de la Llave
14400         31                          Yucatán
14880         32                        Zacatecas

Ahora Veamos todos los datos de delitos de una entidad en específico. Por ejemplo, Nuevo león

In [23]:
datos_long[datos_long['clave_ent'] == 19].sample(15)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia
85646,2020,19,Nuevo León,Fraude,diciembre,773.0
54756,2018,19,Nuevo León,Acoso sexual,abril,14.0
146929,2024,19,Nuevo León,Allanamiento de morada,agosto,0.0
131581,2023,19,Nuevo León,Amenazas,agosto,556.0
85865,2020,19,Nuevo León,Tráfico de menores,julio,1.0
116333,2022,19,Nuevo León,Falsedad,julio,16.0
116475,2022,19,Nuevo León,Otros delitos contra la sociedad,enero,0.0
147022,2024,19,Nuevo León,Electorales,octubre,0.0
85664,2020,19,Nuevo León,Homicidio,mayo,109.0
85512,2020,19,Nuevo León,Contra el medio ambiente,abril,0.0
147313,2024,19,Nuevo León,Violación equiparada,agosto,0.0
147338,2024,19,Nuevo León,Violencia de género en todas sus modalidades d...,diciembre,0.0
24326,2016,19,Nuevo León,Otros delitos del Fuero Común,diciembre,242.0
85652,2020,19,Nuevo León,Fraude,mayo,108.0
85914,2020,19,Nuevo León,Violencia familiar,junio,1569.0

In [24]:
datos_long[(datos_long['clave_ent'] > 19) &  (datos_long['clave_ent'] < 24) & (datos_long['tipo_de_delito'] == 'Homicidio')].sample(15)

        anio  clave_ent       entidad tipo_de_delito nombre_mes  frecuencia
87580   2020         23  Quintana Roo      Homicidio    febrero       131.0
41496   2017         23  Quintana Roo      Homicidio      abril        30.0
148060  2024         21        Puebla      Homicidio    febrero        93.0
26138   2016         23  Quintana Roo      Homicidio  diciembre        16.0
24696   2016         20        Oaxaca      Homicidio      abril       144.0
40056   2017         20        Oaxaca      Homicidio      abril       189.0
25186   2016         21        Puebla      Homicidio    octubre        93.0
71266   2019         21        Puebla      Homicidio    octubre       136.0
25662   2016         22     Querétaro      Homicidio      junio        30.0
101976  2021         21        Puebla      Homicidio      abril       105.0
117821  2022         22     Querétaro      Homicidio      julio        47.0
40059   2017         20        Oaxaca      Homicidio      enero       111.0
118296  2022         23  Quintana Roo      Homicidio      abril       144.0
86623   2020         21        Puebla      Homicidio      marzo       121.0
40063   2017         20        Oaxaca      Homicidio      marzo       115.0

### Valores de fechas

Finalmente, queremos tener una columna "fecha". Actualmente tenemos el año y el nombre del mes, pero no tenemos como tal una columna que tenga un tipo de dato fecha. Eso hace que filtrar por fecha sea complicado.

Por ejemplo, si queremos conocer todos los homicidios de Oaxaca en enero 2024, haríamos lo siguiente:

In [25]:
datos_long[
    (datos_long['clave_ent'] == 20) &
    (datos_long['tipo_de_delito'] == 'Homicidio') &
    (datos_long['anio'] == 2024) &
    (datos_long['nombre_mes'] == 'enero') 
]

        anio  clave_ent entidad tipo_de_delito nombre_mes  frecuencia
147579  2024         20  Oaxaca      Homicidio      enero       157.0

Creemos una columna de fecha. 

Primero tenemos que convertir el nombre de mes a un número, en donde 1 es enero, 2 febrero, etc.

In [26]:
datos_long.sample(2)

       anio  clave_ent  entidad tipo_de_delito nombre_mes  frecuencia
55387  2018         20   Oaxaca  Falsificación      marzo        26.0
57792  2018         25  Sinaloa    Feminicidio      abril         3.0

In [27]:
datos_long["nueva_columna"] = "dato vacío"
datos_long.sample(6)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna
51203,2018,11,Guanajuato,Otros delitos contra la sociedad,septiembre,0.0,dato vacío
90506,2020,29,Tlaxcala,Lesiones,diciembre,20.0,dato vacío
77468,2020,2,Baja California,Falsificación,mayo,7.0,dato vacío
93239,2021,3,Baja California Sur,Delitos cometidos por servidores públicos,septiembre,26.0,dato vacío
72137,2019,23,Quintana Roo,Electorales,julio,0.0,dato vacío
152244,2024,30,Veracruz de Ignacio de la Llave,Corrupción de menores,abril,3.0,dato vacío

In [28]:
# Diccionario de ayuda para convertir
meses = {
    "enero": 1,
    "febrero": 2,
    "marzo": 3,
    "abril": 4,
    "mayo": 5,
    "junio": 6,
    "julio": 7,
    "agosto": 8,
    "septiembre": 9,
    "octubre": 10,
    "noviembre": 11,
    "diciembre": 12
}

datos_long['mes'] = datos_long['nombre_mes'].map(meses)
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes
115727,2022,18,Nayarit,Acoso sexual,septiembre,7.0,dato vacío,9
64461,2019,7,Chiapas,Electorales,noviembre,0.0,dato vacío,11
73691,2019,26,Sonora,Incesto,septiembre,0.0,dato vacío,9
120760,2022,28,Tamaulipas,Narcomenudeo,febrero,15.0,dato vacío,2
144885,2024,14,Jalisco,Secuestro,noviembre,0.0,dato vacío,11

In [29]:
datos_long["frecuencia_mas_10"] = datos_long["frecuencia"] + 10
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes,frecuencia_mas_10
54775,2018,19,Nuevo León,Allanamiento de morada,marzo,34.0,dato vacío,3,44.0
87908,2020,24,San Luis Potosí,Amenazas,mayo,218.0,dato vacío,5,228.0
68002,2019,14,Jalisco,Otros delitos contra la sociedad,octubre,0.0,dato vacío,10,10.0
58021,2018,25,Sinaloa,Tráfico de menores,agosto,0.0,dato vacío,8,10.0
2576,2015,6,Colima,Falsedad,mayo,0.0,dato vacío,5,10.0

In [30]:
datos_long["anio_mes"] = datos_long["anio"].astype(str) + datos_long["mes"].astype(str)
datos_long.sample(6)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes,frecuencia_mas_10,anio_mes
29492,2016,30,Veracruz de Ignacio de la Llave,Fraude,mayo,120.0,dato vacío,5,130.0,20165
91486,2020,31,Yucatán,Narcomenudeo,octubre,16.0,dato vacío,10,26.0,202010
65891,2019,10,Durango,Despojo,septiembre,32.0,dato vacío,9,42.0,20199
267,2015,1,Aguascalientes,Lesiones,enero,228.0,dato vacío,1,238.0,20151
50578,2018,10,Durango,Falsedad,octubre,1.0,dato vacío,10,11.0,201810
11697,2015,25,Sinaloa,Falsedad,noviembre,1.0,dato vacío,11,11.0,201511

In [31]:
# yyyy-mm-dd, yy-mm-dd, yymmdd, yyyy/dd/mm

In [32]:
# Agregamos la columna de fecha juntando el año y el mes
datos_long['fecha'] = pd.to_datetime(datos_long['anio'].astype(str) + datos_long['mes'].astype(str), format='%Y%m')
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,nueva_columna,mes,frecuencia_mas_10,anio_mes,fecha
42338,2017,25,Sinaloa,Daño a la propiedad,diciembre,72.0,dato vacío,12,82.0,201712,2017-12-01
96459,2021,9,Ciudad de México,Violencia de género en todas sus modalidades d...,enero,0.0,dato vacío,1,10.0,20211,2021-01-01
114546,2022,15,México,Otros delitos contra la familia,junio,0.0,dato vacío,6,10.0,20226,2022-06-01
18677,2016,7,Chiapas,Violación equiparada,julio,17.0,dato vacío,7,27.0,20167,2016-07-01
85644,2020,19,Nuevo León,Fraude,abril,124.0,dato vacío,4,134.0,20204,2020-04-01

In [33]:
# Eliminamos las columnas que ya no necesitamos
datos_long = datos_long.drop(columns=['nueva_columna'])
datos_long.sample(5)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,mes,frecuencia_mas_10,anio_mes,fecha
44102,2017,28,Tamaulipas,Tráfico de menores,diciembre,0.0,12,10.0,201712,2017-12-01
16084,2016,2,Baja California,Incesto,febrero,0.0,2,10.0,20162,2016-02-01
118080,2022,23,Quintana Roo,Aborto,abril,0.0,4,10.0,20224,2022-04-01
79750,2020,7,Chiapas,Amenazas,octubre,43.0,10,53.0,202010,2020-10-01
18728,2016,8,Chihuahua,Aborto,mayo,0.0,5,10.0,20165,2016-05-01

Veamos los homicidios en oaxaca de enero 2024 a la fecha

In [34]:
datos_long[
    (datos_long.tipo_de_delito == "Homicidio") &
    (datos_long.clave_ent == 20) &
    (datos_long.fecha >= '2024-01-01')
].sort_values('fecha')

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,frecuencia,mes,frecuencia_mas_10,anio_mes,fecha
147579,2024,20,Oaxaca,Homicidio,enero,157.0,1,167.0,20241,2024-01-01
147580,2024,20,Oaxaca,Homicidio,febrero,170.0,2,180.0,20242,2024-02-01
147583,2024,20,Oaxaca,Homicidio,marzo,190.0,3,200.0,20243,2024-03-01
147576,2024,20,Oaxaca,Homicidio,abril,208.0,4,218.0,20244,2024-04-01
147584,2024,20,Oaxaca,Homicidio,mayo,236.0,5,246.0,20245,2024-05-01
147582,2024,20,Oaxaca,Homicidio,junio,202.0,6,212.0,20246,2024-06-01
147581,2024,20,Oaxaca,Homicidio,julio,0.0,7,10.0,20247,2024-07-01
147577,2024,20,Oaxaca,Homicidio,agosto,0.0,8,10.0,20248,2024-08-01
147587,2024,20,Oaxaca,Homicidio,septiembre,0.0,9,10.0,20249,2024-09-01
147586,2024,20,Oaxaca,Homicidio,octubre,0.0,10,10.0,202410,2024-10-01
147585,2024,20,Oaxaca,Homicidio,noviembre,0.0,11,10.0,202411,2024-11-01
147578,2024,20,Oaxaca,Homicidio,diciembre,0.0,12,10.0,202412,2024-12-01

In [35]:
datos_finales = datos_long[['anio', 'clave_ent', 'entidad', 'tipo_de_delito', 'nombre_mes', 'fecha', 'frecuencia']]
datos_finales.head(2)

,anio,clave_ent,entidad,tipo_de_delito,nombre_mes,fecha,frecuencia
0,2015,1,Aguascalientes,Aborto,abril,2015-04-01,0.0
1,2015,1,Aguascalientes,Aborto,agosto,2015-08-01,0.0

Ya que tenemos muestros datos bien estructurados, los podemos guardar en nuestra computadora. Los guardaremos con el nombre "delitos.csv"

In [ ]:
datos_finales.to_csv('data/delitos.csv', index=False)
#hola